theme = "ahernp"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"
color-modes = true
rulers = [88]
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"

[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
cursor-line = "disable"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "file-modification-indicator"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
A-y = [":new", ":insert-output yazi", ":buffer-close!", ":redraw"]

[keys.normal."space"]
"<" = "file_picker_in_current_buffer_directory"

[keys.select]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
