version: '3'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD
    devenv:
        build:
            context: ./devenv
        image: ubuntu1804:devenv
        environment:
            - AHERNP_DATABASE_USER
            - AHERNP_DATABASE_PASSWORD
            - AHERNP_DATABASE_NAME
            - POSTGRES_PASSWORD
            - DJANGO_SECRET_KEY
        command: /root/inotify.sh
        volumes:
            - .:/work
        ports:
            - "8000:8000"
    nginx:
        image: nginx:stable
        volumes:
            - ./devenv/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./devenv/uwsgi_params:/opt/ahernp/uwsgi_params
            - ./ahernp.com/uwsgi.sock:/opt/ahernp/uwsgi.sock
            - ./ahernp.com/static:/opt/ahernp/static
            - ./ahernp.com/media:/opt/ahernp/media
            - ./ahernp.com/templates:/opt/ahernp/templates
        depends_on:
            - webapp
        ports:
            - "80:80"
    golang:
        image: golang:1.12
        environment:
            GO111MODULE: "on"
        volumes:
            - ./go:/go
        ports:
            - "8080:8080"
    node:
        image: node:9
        working_dir: /node
        command: bash -c "npm install && npm start"
        volumes:
            - ./ahernp.com/pages/pagesjs:/node
        ports:
            - "3000:3000"
    webapp:
        build:
            context: ./ahernp.com
        image: webapp:ahernp
        environment:
            - AHERNP_DATABASE_USER
            - AHERNP_DATABASE_PASSWORD
            - AHERNP_DATABASE_NAME
            - POSTGRES_PASSWORD
            - DJANGO_SECRET_KEY
        command: uwsgi --socket /opt/ahernp/uwsgi.sock --module project.wsgi --chmod-socket=777
        volumes:
            - ./ahernp.com:/opt/ahernp
        working_dir: /opt/ahernp
        depends_on:
            - db
