---
- name: Install Vim
  apt: pkg=vim

- stat: path=/home/{{userid}}/.vim
  register: vim_link

- file: src={{config_base_dir}}/roles/vim/files/.vim dest='/home/{{userid}}/.vim' owner={{userid}} group={{userid}} state=link
  when: not vim_link.stat.exists

- stat: path=/home/{{userid}}/.vimrc
  register: vimrc_link

- file: src={{config_base_dir}}/roles/vim/files/.vimrc dest=/home/{{userid}}/.vimrc owner={{userid}} group={{userid}} state=link
  when: not vimrc_link.stat.exists
