---

- name: Create docker-solr on the local machine
  hosts: localhost
  connection: local

  vars:
  - container_name: my-solr
  - core_name: pages

  tasks:
  - name: Fail if docker is not installed
    command: docker

  - name: Create solr docker container {{container_name}}
    docker:
      name: "{{container_name}}"
      hostname: solr
      image: solr:6.6
      state: started
      restart_policy: always
      pull: always
      ports: 8983:8983

  - name: Wait for container {{container_name}} to start
    wait_for:
      port: 8983
      delay: 10

  - name: Create core {{core_name}} on container {{container_name}}
    command: docker exec {{container_name}} bin/solr create_core -c {{core_name}}

  - name: Reset schema of core {{core_name}} on container {{container_name}}
    command: docker cp files/{{core_name}}-managed-schema {{container_name}}:/opt/solr/server/solr/pages/conf/managed-schema

  - name: Restart container {{container_name}}
    command: docker restart {{container_name}}

  - name: Wait for container {{container_name}} to start
    wait_for:
      port: 8983
      delay: 10

  - name: Copy {{core_name}} data to container {{container_name}}
    command: docker cp files/{{core_name}}-data.json {{container_name}}:/opt/solr/{{core_name}}-data.json

  - name: Load data into core {{core_name}} on container {{container_name}}
    command: docker exec {{container_name}} bin/post -c {{core_name}} {{core_name}}-data.json
