---
# Setup development environment for development. Tested on devpc.

# Clone repositories
- name: Checkout repositories
  git: >
    repo=git@github.com:ahernp/{{item}}.git
    dest=/home/{{userid}}/code/{{item}}
    update=no
    accept_hostkey=yes
  with_items:
    - ahernp.com
    - config
    - django-bugtracker
    - django-feedreader
    - django-monitoring
    - DMCM

- name: Populate secrets.json
  template: src=secrets.json dest=/home/{{userid}}/code/ahernp.com/ahernp/secrets.json

- name: Setup virtualenv
  pip: >
    virtualenv="/home/{{userid}}/.virtualenvs/ahernp"
    requirements=/home/{{userid}}/code/ahernp.com/requirements/local.txt

# PostgreSQL
- name: Create PostgreSQL database
  postgresql_db: name={{database_name}} login_user=postgres
  become: yes
  become_user: postgres

- name: Create user in PostgreSQL
  postgresql_user: >
    db={{database_name}}
    name={{database_userid}}
    password={{database_password}}
    role_attr_flags=CREATEDB
    login_user=postgres
  become: yes
  become_user: postgres

- name: Grant access to database
  postgresql_privs: >
    db={{database_name}}
    roles={{database_userid}}
    privs=ALL
    type=database
    login_user=postgres
  become: yes
  become_user: postgres
