---
# Setup local PC; Tested on Ubuntu 15.10

- name: Install apt packages
  apt: pkg={{item}} state=installed
  with_items:
       - ack-grep
       - byobu
       - chromium-browser
       - curl
       - fabric
       - flashplugin-installer
       - geany
       - git
       - gksu
       - gnucash
       - htop
       - icedtea-plugin
       - inkscape
       - ipython
       - keepassx
       - libpq-dev
       - mercurial
       - numlockx
       - openjdk-7-jre
       - pandoc
       - postgresql
       - postgresql-contrib
       - python-dev
       - python-pip
       - python-sphinx
       - rar
       - speedcrunch
       - sqlite3
       - ssh
       - subversion
       - synapse
       - synaptic
       - tasksel
       - traceroute
       - tree
       - vim
       - virtualenvwrapper
       - zsh
  become: yes


# ssh
- name: Check link to ~/.ssh
  stat: path=/home/{{userid}}/.ssh
  register: ssh_link

- name: Create link to ~/.ssh
  file: src=/home/{{userid}}/Desktop/work/dot.ssh dest=/home/{{userid}}/.ssh owner={{userid}} group={{userid}} state=link
  when: not ssh_link.stat.exists


# Vim
- name: Check link ~/.vimrc
  stat: path=/home/{{userid}}/.vimrc
  register: vimrc_link

- name: Create link ~/.vimrc
  file: src={{config_base_dir}}/roles/devpc/files/.vimrc dest=/home/{{userid}}/.vimrc owner={{userid}} group={{userid}} state=link
  when: not vimrc_link.stat.exists

- name: Vim - checkout vundle repo
  git: repo=https://github.com/gmarik/vundle.vim.git dest='/home/{{userid}}/.vim/bundle/vundle.vim'

- name: Check link ~/.vim/colors
  stat: path=/home/{{userid}}/.vim/colors
  register: vimcolors_link

- name: Create link ~/.vim/colors
  file: src={{config_base_dir}}/roles/devpc/files/.vim/colors dest=/home/{{userid}}/.vim/colors owner={{userid}} group={{userid}} state=link
  when: not vimcolors_link.stat.exists

- name: Vim - run bundle install
  command: vim +BundleInstall +qall
  when: not vimcolors_link.stat.exists


# Byobu
- name: Check file ~/.byobu/backend
  stat: path=/home/{{userid}}/.byobu/backend
  register: byobubackend_file

- name: Set byobu backend
  command: byobu-select-backend screen
  when: not byobubackend_file.stat.exists
